name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: daklyann/refactai:test
      volumes:
        - /:/home/runner/work/PA_TEST_ACTION/PA_TEST_ACTION
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

