name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: daklyann/refactai:test
      volumes:
        - /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/
    steps:
      - name: python run
        run: ls -la

