name: CI
on:
  push:
    branches: [ test ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: daklyann/refactai:test
      volumes:
        - .github/workflow:/data
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: run documentation script
        run: python3 /data/src/docGeneration/main.py
      - name: Generate commentary check
        run: python3 /data/src/docGeneration/CommentaryCheck.py

