name: CI
on:
  push:
    branches: [ test ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: daklyann/refactai:test
      options: -v /home/runner/work/${{ github.event.repository.name }}:/data
#      volumes:
#        - /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/data
    steps:
      - name: python run
        run: cat /data/PA_TEST_ACTION/main.py
      - name: test
        run: cat /data/PA_TEST_ACTION/PA_TEST_ACTION/main.py

