name: CI
on:
  push:
    branches: [ test ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: daklyann/refactai:test
      volumes:
        - /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/data
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v2
      - name: run documentation script
        run: python3 /data/.github/workflows/src/docGeneration/main.py
      - name: Generate commentary check
        run: python3 /data/.github/workflows/src/docGeneration/CommentaryCheck.py
      - name: test exit container
        run: exit
      - name: commit
        run:  git add ./output/* -f && git commit -m "Add documentation + Commentary" -a && git push origin main

